name: iq_mall
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.4+15

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  #  cool_alert: ^2.0.1
  #  permission_handler_platform_interface: ^4.0.2
  permission_handler: ^12.0.1

  #  image_pickers: ^2.0.5+2
  multi_image_picker_view: ^3.0.0
  image_picker: ^1.1.2
  loading_animation_widget: ^1.2.0+4
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.12.3
  timeago: ^3.5.0
  shrink_sidemenu: ^2.0.0+2-null-safety
  persistent_bottom_nav_bar: ^6.2.1
  device_info_plus:

  carousel_slider: ^5.0.0
  mime_type:
  random_string: ^2.3.1
  dots_indicator: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  country_picker: ^2.0.16
  sign_in_with_apple: ^7.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_keyboard_visibility: ^6.0.0
  whatsapp_unilink: ^2.0.1+1
  sms_autofill: ^2.3.0
  vibration: ^3.1.5
  uuid: ^4.5.2
  flutter_cache_manager: ^3.3.1
  dio: ^5.9.0
  http_auth: ^1.0.0
  geocoding: ^3.0.0
  firebase_analytics: ^12.1.0
  firebase_messaging: ^16.1.0
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  google_sign_in: ^6.3.0
  card_swiper: ^3.0.1
  get: ^4.7.2
  progressive_image: ^2.0.1
  pin_code_fields:
  photo_view: ^0.14.0
  awesome_dialog: ^3.0.2
  package_info_plus: ^9.0.0
  http: ^1.6.0
  quickalert: ^1.1.0
  shared_preferences: ^2.0.15
  share_plus: ^12.0.1
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.0.0
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.3.8
  fluttertoast: ^8.2.8
  intl: ^0.20.2
  flutter_svg: ^2.0.0
  url_launcher: ^6.2.4
  geolocator: ^13.0.2
  multi_select_flutter: ^4.0.0
  flutter_multiselect: ^1.0.0
  flutter_html: 3.0.0-beta.2
  webview_flutter: ^4.13.0
  file_picker: ^8.3.7
  video_player: ^2.10.0
  shimmer: ^3.0.0
  html_unescape: ^2.0.0
  flutter_avif: ^3.1.0
  animated_react_button: ^0.0.4
  visibility_detector: ^0.4.0+2
  chewie: ^1.4.0

  transitioned_indexed_stack: ^1.0.2
  toastification: ^1.2.1
  animated_icon: ^0.0.9
  curved_labeled_navigation_bar: ^2.0.2
  bottom_navbar_with_indicator: ^0.0.9
  html_editor_enhanced: 2.6.0
  flutter_xlider: ^3.5.0
  app_links: ^6.4.0
  restart_app: ^1.3.2

  pdf: ^3.11.0
  printing: ^5.13.4
  path_provider: ^2.1.4
  open_filex: ^4.5.0

  dropdown_button2: ^2.3.9
  map_launcher: ^3.5.0
  awesome_notifications: ^0.10.1
  percent_indicator: ^4.2.3

  pdfx: ^2.6.0
  android_intent_plus: ^6.0.0

  #  better_player:
  #    git:
  #      url: https://github.com/tintran-dev/betterplayer.git

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

# setting splash screen
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.

  #   image_width: 1000
  #   image_height: 1000
  color: "0f0649"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: "assets/images/splash_icon.png"

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
  # see the Android 12 section below.
  branding: "assets/images/powered_gold.png"

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #   branding_mode: bottom

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.PNG"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: "assets/images/splash_icon.png"
    branding: "assets/images/powered_gold.png"

    # Splash screen background color.
    color: "#0f0649"

    # App icon background color.
    #icon_background_color: "#111111"
    # The branding property allows you to specify an image used as branding in the splash screen.
    # branding: "assets/images/powered_v.png"
    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  #web: false
  # Platform specific images can be specified with the following parameters, which will override
  # the respective image parameter.  You may specify all, selected, or none of these parameters:
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.png
  #image_dark_web: assets/splash-invert-web.png
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_dark_ios: assets/dart_dark-ios.png
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  ios_content_mode: scaleAspectFit
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape
  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: false
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/navigation_icons/
    - assets/fonts/Cairo-Regular.ttf
    - assets/fonts/Cairo-Bold.ttf
    - assets/data/transactions.json
  fonts:
    - family: ArabicFont
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
assets/assets/facebook_pop:
